# Default values for sormas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

runtime: kata

image:
  pullPolicy: IfNotPresent
  sormas: 
    name: robbmue/sormas_no_autodeploy
    version: latest
  postgres:
    name: robbmue/sormas_postgres_ba
    version: latest

latitude: 52.2109803
longitude: 10.5314925
map_zoom: 10
tz: europe/berlin
locale: de-DE
domain_name: sormas
epidprefix: DEU
separator: \;
disable_certbot: true
letsencrypt_mail: 
geo_uuid: 
devmode: false
json_logging: false
prometheus_servers: 127.0.0.1

sormas: 
  postgres_user: sormas_user
  postgres_password: password
  url: https://github.com/hzi-braunschweig/SORMAS-Project/releases/download/
  docker_version: 2.13.2
  version: 1.51.1
  domain: k8smaster
  appserver_jvm_max: 4096m
  limits: 
    mem: 4300M
    cpus: 2000m
  org:
    id: HZI_TEST
    name: 'HZI Braunschweig'
  s2s:
    cert_pass: password
    rest_passweord: passwordpassword

db:
  host: postgres
  name: sormas
  name_audit: sormas_audit
  jdbc_maxpoolsize: 128
  limits: 
    mem: 2000M
    cpus: 2000m

mail:
  host: localhost
  from: root@localhost
  sender_address: noreply@sormas-docker-test.com
  sender_name: SORMAS

custombranding: 
  enabled: false
  name: SORMAS
  logo_path: none
  use_loginsidebar: true
  loginbackground_path: 

cacerts_pass: changeit
keystore_pass: changeit

casearchivedays: 90
eventarchivedays: 90