apiVersion: v1
kind: ConfigMap
metadata:
  name: sormas-cm
  namespace: {{ .Release.Name }}
data:

  SORMAS_POSTGRES_USER: {{ .Values.sormas.postgres_user }}
  SORMAS_DOCKER_VERSION: {{ .Values.sormas.docker_version | quote }}
  SORMAS_VERSION: {{ .Values.sormas.version | quote }}
  SORMAS_SERVER_URL: {{ .Release.Name }}.{{ .Values.sormas.domain }}
  SORMAS_URL: {{ .Values.sormas.url }}
  APPSERVER_JVM_MAX: {{ .Values.sormas.appserver_jvm_max }}

  LATITUDE: {{ .Values.latitude | quote }}
  LONGITUDE: {{ .Values.longitude | quote }}
  MAP_ZOOM: {{ .Values.map_zoom | quote }}
  TZ: {{ .Values.tz }}
  LOCALE: {{ .Values.locale }}
  DOMAIN_NAME: {{ .Values.domain_name }}
  EPIDPREFIX: {{ .Values.epidprefix }}
  SEPARATOR: {{ .Values.separator }}
  DISABLE_CERTBOT: {{ .Values.disable_certbot | quote }}
  LETSENCRYPT_MAIL: {{ default "" .Values.letsencrypt_mail | quote }}
  GEO_UUID: {{ default "" .Values.geo_uuid | quote }}
  DEVMODE: {{ .Values.devmode | quote }}
  JSON_LOGGING: {{ .Values.json_logging | quote }}
  PROMETHEUS_SERVERS: {{ .Values.prometheus_servers | quote }}

  DB_HOST: {{ .Values.db.host }}
  DB_NAME: {{ .Values.db.name }}
  DB_NAME_AUDIT: {{ .Values.db.name_audit }}
  DB_JDBC_MAXPOOLSIZE: {{ .Values.db.jdbc_maxpoolsize | quote }}

  MAIL_HOST: {{ .Values.mail.host }}
  MAIL_FROM: {{ .Values.mail.from }}
  EMAIL_SENDER_ADDRESS: {{ .Values.mail.sender_address }}
  EMAIL_SENDER_NAME: {{ .Values.mail.sender_name }}

  CUSTOMBRANDING_ENABLED: {{ .Values.custombranding.enabled | quote }}
  CUSTOMBRANDING_NAME: {{ .Values.custombranding.name }}
  CUSTOMBRANDING_LOGO_PATH: {{ .Values.custombranding.logo_path }}
  CUSTOMBRANDING_USE_LOGINSIDEBAR: {{ .Values.custombranding.use_loginsidebar | quote}}
  CUSTOMBRANDING_LOGINBACKGROUND_PATH: {{ default "" .Values.custombranding.loginbackground_path | quote }}

  SORMAS_ORG_ID: {{ .Values.sormas.org.id }}
  SORMAS_ORG_NAME: {{ .Values.sormas.org.name }}
  SORMAS2SORMAS_ENABLED: ''
  SORMAS_S2S_CERT_PASS: {{ default "" .Values.sormas.s2s.cert_pass | quote }}
  SORMAS_S2S_REST_PASSWORD: {{ default "" .Values.sormas.s2s.rest_password | quote }}
  
  CACERTS_PASS: {{ default "" .Values.cacerts_pass }}
  KEYSTORE_PASS: {{ default "" .Values.keystore_pass }}
  CASEARCHIVEDAYS: {{ default "" .Values.casearchivedays | quote }}
  EVENTARCHIVEDAYS: {{ default "" .Values.eventarchivedays | quote }}