apiVersion: apps/v1
kind: Deployment
metadata:
  name: sormas
  namespace: {{ .Release.Name }}
spec: 
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector: 
    matchLabels:
      run: sormas
  template:
    metadata:
      labels:
        run: sormas
    spec:
      runtimeClassName: {{ .Values.runtime }}
      containers:
        - image: {{ .Values.image.sormas.name }}:{{ .Values.image.sormas.version}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: sormas
          resources:
            limits:
              memory: {{ .Values.sormas.limits.mem }}
              cpu: {{ .Values.sormas.limits.cpus }}
          ports: 
          - containerPort: 6080
            protocol: TCP
            name: payara
          - containerPort: 6048
            protocol: TCP
            name: payara-admin
          volumeMounts:
          - name: custom
            mountPath: /opt/sormas/custom
          - name: sormas-logs
            mountPath: /opt/domains/sormas/logs
          livenessProbe:
            httpGet:
              path: /sormas-ui/login
              port: 6080
            initialDelaySeconds: 300
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /sormas-ui/login
              port: 6080
            initialDelaySeconds: 100
            periodSeconds: 30
          env: 
          - name: SORMAS_POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                key: password
                name: secret-postgres
          envFrom: 
          - configMapRef:
              name: sormas-cm
      volumes: 
      - name: custom
        persistentVolumeClaim:
          claimName: custom
      - name: sormas-logs
        emptyDir: {}