apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sormas
  namespace: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.sormas.domain }}      
    http:
      paths:
      - path: /
        backend:
          serviceName: sormas 
          servicePort: 80