apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom
  namespace: {{ .Values.metadata.namespace }}
spec: 
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi