apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom
  namespace: {{ .Release.Name }}
spec: 
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi