kind: Secret
apiVersion: v1
metadata: 
  name: secret-postgres
  namespace: {{ .Release.Name }}
data: 
  password: {{ .Values.sormas.postgres_password | b64enc }}
  username: {{ .Values.sormas.postgres_user | b64enc }}
  pgpass: {{ printf "%s:%d:%s:%s:%s" .Values.db.host 5432 .Values.db.name .Values.sormas.postgres_user .Values.sormas.postgres_password | b64enc }}