kind: Secret
apiVersion: v1
metadata: 
  name: secret-postgres
  namespace: {{ .Release.Name }}
data: 
  password: {{ .Values.sormas.postgres_password | b64enc }}
  username: {{ print "postgres" | b64enc }}