apiVersion: v1
kind: Service
metadata:
  name: sormas
  namespace: {{ .Release.Name }}
spec: 
  selector:
    run: sormas
  ports: 
    - name: http
      port: 80
      #protocol: TCP
      targetPort: payara
    - name: import
      port: 6080
      targetPort: payara
