apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.metadata.namespace }}
spec: 
  selector:
    app: postgres
  ports: 
    - protocol: TCP
      port: 5432
      targetPort: 5432