apiVersion: v1
kind: Service
metadata:
  name: sormas
  namespace: {{ .Values.metadata.namespace }}
spec: 
  selector:
    run: sormas
  ports: 
    - protocol: TCP
      port: 80
      targetPort: payara
