apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: ab-postgres
  namespace: {{ .Release.Name }}
spec:
  clientConfig:
    service:
      name: postgres
      port: 5432
      scheme: postgresql
  secret:
    name: secret-postgres
  secretTransforms:
  - renameKey:
      from: username
      to: POSTGRES_USER
  - renameKey:
      from: password
      to: POSTGRES_PASSWORD
  type: postgres
  version: "10.14"