apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: ab-postgres
  namespace: ga-test-kata #{{ .Release.Name }}
spec:
  clientConfig:
    service:
      name: postgres
      port: 5432
      scheme: postgresql
  secret:
    name: secret-postgres
  type: postgres