apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      runtimeClassName: {{ .Values.runtime }}
      containers:
        - name: postgres
          image: {{ .Values.image.postgres.name }}:{{ .Values.image.postgres.version}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
          ports: 
          - containerPort: 5432
            name: postgres
          volumeMounts:
          - name: postgres
            mountPath: /var/lib/postgresql/data
            subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secret-postgres
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: sormas-cm
            - name: DB_NAME_AUDIT
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME_AUDIT
                  name: sormas-cm
            - name: SORMAS_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secret-postgres
            - name: SORMAS_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: SORMAS_POSTGRES_USER
                  name: sormas-cm
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: sormas-cm
          resources:
            limits:
              memory: {{ .Values.db.limits.mem }}
              cpu: {{ .Values.db.limits.cpus }}
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres
        namespace: {{ .Release.Name }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi      
          

                