apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-test
spec: 
  selector:
    app: postgres
  ports: 
    - protocol: TCP
      port: 5432
      targetPort: postgres